In [2]:
import gzip
import pandas as pd
import json
from collections import defaultdict
import itertools
data_users3 = []
with gzip.open('D:/Vortess/DWH/10_Datasets/Google Local Review/places.clean.json.gz') as g:
    for line in itertools.islice(g, 0, 10):        
        data_users3.append(eval(line))
        
df2 = pd.DataFrame.from_dict(data_users3)

In [3]:
df2

,name,price,address,hours,phone,closed,gPlusPlaceId,gps
0,Diamond Valley Lake Marina,None,"[2615 Angler Ave, Hemet, CA 92545]","[[Monday, [['6:30 am--4:15 pm']]], [Tuesday, [...",(951) 926-7201,False,104699454385822125632,"[33.703804, -117.003209]"
1,Blue Ribbon Cleaners,None,"[Parole, Annapolis, MD]",None,(410) 266-6123,False,103054478949000078829,"[38.979759, -76.547538]"
2,Portofino,None,"[ул. Тутаева, 1, Nazran, Ingushetia, Russia, 3...","[[Monday, [['9:30 am--9:00 pm']]], [Tuesday, [...",8 (963) 173-38-38,False,109810290098030327104,"[43.22776, 44.762726]"
3,T C's Referee Sports Bar,$$,"[5322 W 26th St, Sioux Falls, SD 57106]","[[Monday, [['11:00 am--10:00 pm']]], [Tuesday,...",(605) 361-2208,False,100327153115986850675,"[43.529494, -96.792244]"
4,Carrefour - Palembang Square,None,"[Jl. Angkatan 45, Kompleks Palembang Square, S...","[[Monday, [['8:00 am--9:00 pm']]], [Tuesday, [...",(0711) 359918,False,103368487323937936043,"[-2.976256, 104.742662]"
5,Pizzeria Montana,None,"[Stuttgarter Straße 44, 75378 Bad Liebenzell, ...",None,07052 933486,False,103903929544828620241,"[48.767817, 8.75612]"
6,Single Tree Inn,None,"[2033 W Oklahoma Ave, Ulysses, KS 67880]",None,(620) 356-1500,False,103848836623683146185,"[37.576427, -101.386182]"
7,Sekolah Menengah Kebangsaan Tun Abang Haji Openg,None,"[Jalan Demak, Petra Jaya, Kuching, Sarawak, Ma...",None,None,False,114537653478141145113,"[1.572255, 110.362958]"
8,天山湯治郷,None,"[208 Yumotochaya, Hakone, Ashigarashimo Distri...",None,0460-86-4126,False,100062881646354125752,"[35.224978, 139.088382]"
9,Old Chicago,$$,"[17960 NW Evergreen Pkwy, Beaverton, OR 97006]","[[Monday, [['11:00 am--1:00 am']]], [Tuesday, ...",(503) 533-4650,False,118222137795476771294,"[45.535176, -122.862242]"